version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6
  sdkman: joshdholtz/sdkman@0.2.0

executors:
  openjdk-8:
    docker:
      - image: cimg/openjdk:8.0

jobs:
  sbt:
    parameters:
      executor:
        type: "string"
    executor:
      name: << parameters.executor >>
    steps:
      - heroku/install
      - sdkman/setup-sdkman
      - sdkman/sdkman-install:
          candidate: sbt
          version: 1.4.1
      - checkout
      - run: sbt "^publishLocal"
      - run: sbt scripted

workflows:
  ci:
    jobs:
      - sbt:
          executor: "openjdk-8"
